version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4477:4477'
    environment:
      PRISMA_CONFIG: |
        port: 4477
        databases:
          default:
            connector: postgres
            #host: host.docker.internal
            host: 192.168.200.190
            port: 5432
            database: prisma
            user: postgres
            password: Password1
            migrations: true
            rawAccess: true
